// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WebProgrammingProject.Models;

namespace WebProgrammingProject.Migrations
{
    [DbContext(typeof(ComputerDbContext))]
    [Migration("20181207002821_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebProgrammingProject.Models.Computer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CPUID");

                    b.Property<int>("GPUID");

                    b.Property<int>("HDDSize");

                    b.Property<int>("ManufacturerID");

                    b.Property<string>("ModelName");

                    b.Property<double>("Price");

                    b.Property<int>("RAMSize");

                    b.Property<int>("SSDSize");

                    b.Property<double>("ScreenSize");

                    b.Property<int>("UserID");

                    b.Property<int>("Year");

                    b.HasKey("ID");

                    b.ToTable("Computers");
                });

            modelBuilder.Entity("WebProgrammingProject.Models.CPU", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Architecture");

                    b.Property<double>("Frequency");

                    b.Property<string>("Name");

                    b.Property<int>("Power");

                    b.HasKey("ID");

                    b.ToTable("CPUs");
                });

            modelBuilder.Entity("WebProgrammingProject.Models.GPU", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Bit");

                    b.Property<string>("Name");

                    b.Property<int>("Power");

                    b.HasKey("ID");

                    b.ToTable("GPUs");
                });

            modelBuilder.Entity("WebProgrammingProject.Models.Manufacturer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("WebProgrammingProject.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("Phone");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
